### ISSUE TITLE
高版本滑动惯性不能用

### ISSUE THREAD

**Issue by Biekangdong** [xmuSistone/PersistentRecyclerView#18]
android 11，子recycleview,的惯性传递一半就不能滑动了,应该是反射禁用问题，大神又解决方法没

**Comment by xmuSistone** [comment]
@Biekangdong 我试了targetSdkVersion=compileSdkVersion=30 是没问题的啊

**Comment by Biekangdong** [comment]
> @Biekangdong 我试了targetSdkVersion=compileSdkVersion=30 是没问题的啊

vivos9  版本11，有这个问题，下面有链接：
https://yangsa123.oss-cn-beijing.aliyuncs.com/WeChat_20220117205847.mp4

**Comment by xmuSistone** [comment]
@Biekangdong 我试了vivo确实有此问题，最新代码已提交，如还有其它问题请再反馈

**Comment by Biekangdong** [comment]
多谢大神，这个可以了，还有我那个PersistentCoordinatorLayout vivos9也有问题，上滑惯性不会传递到recycleview里面，链接：https://yangsa123.oss-cn-beijing.aliyuncs.com/690213f940b516dae4debef8ad43ec21.mp4

**Comment by xmuSistone** [comment]
> 多谢大神，这个可以了，还有我那个PersistentCoordinatorLayout vivos9也有问题，上滑惯性不会传递到recycleview里面，链接：https://yangsa123.oss-cn-beijing.aliyuncs.com/690213f940b516dae4debef8ad43ec21.mp4

@Biekangdong PersistentCoordinatorLayout的问题也已修复，拉最新代码即可

**Comment by Biekangdong** [comment]
PersistentCoordinatorLayout 还有个问题，高api,30或者31，下面反射那个地方会崩溃 



 // Android 9.0及以上，非公开Api接口被禁用，无法获取mDuration字段
        // 此处伪装成系统身份，绕过 @hide 检查
        val metaGetDeclaredField = Class::class.java.getDeclaredMethod("getDeclaredField", String::class.java)
        durationField = metaGetDeclaredField.invoke(scrollerYObj.javaClass, "mDuration") as Field
        durationField.isAccessible = true

报错log
 java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:636)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1031)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1031) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.stone.persistent.library.HookedScroller.<init>(HookedScroller.kt:40)
        at com.stone.persistent.library.PersistentCoordinatorLayout.hookScroller(PersistentCoordinatorLayout.kt:54)
        at com.stone.persistent.library.PersistentCoordinatorLayout.access$hookScroller(PersistentCoordinatorLayout.kt:16)
        at com.stone.persistent.library.PersistentCoordinatorLayout$onFinishInflate$1.onGlobalLayout(PersistentCoordinatorLayout.kt:33)
        at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:1079)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3354)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2230)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8754)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1031)
        at android.view.Choreographer.doCallbacks(Choreographer.java:849)
        at android.view.Choreographer.doFrame(Choreographer.java:779)
        at android.view.Choreographer$FrameHandler.handleMessage(Choreographer.java:954)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:257)
        at android.app.ActivityThread.main(ActivityThread.java:8215)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1031) 
     Caused by: java.lang.NoSuchFieldException: No field mDuration in class Landroid/widget/OverScroller$SplineOverScroller; (declaration of 'android.widget.OverScroller$SplineOverScroller' appears in /system/framework/framework.jar!classes3.dex)
        at java.lang.Class.getDeclaredField(Native Method)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.stone.persistent.library.HookedScroller.<init>(HookedScroller.kt:40) 
        at com.stone.persistent.library.PersistentCoordinatorLayout.hookScroller(PersistentCoordinatorLayout.kt:54) 
        at com.stone.persistent.library.PersistentCoordinatorLayout.access$hookScroller(PersistentCoordinatorLayout.kt:16) 
        at com.stone.persistent.library.PersistentCoordinatorLayout$onFinishInflate$1.onGlobalLayout(PersistentCoordinatorLayout.kt:33) 
        at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:1079) 
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3354) 
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2230) 
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8754) 
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1031) 
        at android.view.Choreographer.doCallbacks(Choreographer.java:849) 
        at android.view.Choreographer.doFrame(Choreographer.java:779) 
        at android.view.Choreographer$FrameHandler.handleMessage(Choreographer.java:954) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:257) 
        at android.app.ActivityThread.main(ActivityThread.java:8215) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1031)

**Comment by xmuSistone** [comment]
@Biekangdong  集成三方库[FreeReflection](https://github.com/tiann/FreeReflection)

**Comment by Biekangdong** [comment]
> > 多谢大神，这个可以了，还有我那个PersistentCoordinatorLayout vivos9也有问题，上滑惯性不会传递到recycleview里面，链接：https://yangsa123.oss-cn-beijing.aliyuncs.com/690213f940b516dae4debef8ad43ec21.mp4
> 
> @Biekangdong PersistentCoordinatorLayout的问题也已修复，拉最新代码即可

大神，还有个荣耀手机也有这个问题
![qq](https://user-images.githubusercontent.com/13655207/153702772-655c001a-f72b-4877-9221-b340be3bffec.jpg)

**Comment by xmuSistone** [comment]
@Biekangdong 荣耀手机问题也适配好了，拉最新代码即可
